const gameQuestionList: GameQuestionInfo[] = [
  {
    qTimer: 10,
    qTopic: "INSERTION",
    qType: "STATE-AFTER-SWAPS",
    contentType: "ARRAY-BARS",
    answerType: "ARRAY-BARS",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "INSERTION",
    qType: "TIME-COMPLEXITY-DIRECT",
    contentType: "TEXT",
    answerType: "TEXT",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "INSERTION",
    qType: "SPACE-COMPLEXITY",
    contentType: "TEXT",
    answerType: "TEXT",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "INSERTION",
    qType: "CHOOSE-PSEUDOCODE",
    contentType: "CODE",
    answerType: "TEXT",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "INSERTION",
    qType: "TIME-COMPLEXITY-FROM-ARRAY",
    contentType: "ARRAY-BARS",
    answerType: "TEXT",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "INSERTION",
    qType: "DRAG-CODE",
    contentType: "DRAGGABLE-CODE",
    answerType: "CHECK-ANSWER",
    hasAnswerOptions: false,
  },
  {
    qTimer: 10,
    qTopic: "INSERTION",
    qType: "DRAG-ARRAY-BARS",
    contentType: "DRAGGABLE-ARRAY-BARS",
    answerType: "CHECK-ANSWER",
    hasAnswerOptions: false,
  },
  {
    qTimer: 10,
    qTopic: "SELECTION",
    qType: "STATE-AFTER-SWAPS",
    contentType: "ARRAY-BARS",
    answerType: "ARRAY-BARS",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "SELECTION",
    qType: "TIME-COMPLEXITY-DIRECT",
    contentType: "TEXT",
    answerType: "TEXT",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "SELECTION",
    qType: "SPACE-COMPLEXITY",
    contentType: "TEXT",
    answerType: "TEXT",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "SELECTION",
    qType: "CHOOSE-PSEUDOCODE",
    contentType: "CODE",
    answerType: "TEXT",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "SELECTION",
    qType: "TIME-COMPLEXITY-FROM-ARRAY",
    contentType: "ARRAY-BARS",
    answerType: "TEXT",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "SELECTION",
    qType: "DRAG-CODE",
    contentType: "DRAGGABLE-CODE",
    answerType: "CHECK-ANSWER",
    hasAnswerOptions: false,
  },
  {
    qTimer: 10,
    qTopic: "SELECTION",
    qType: "DRAG-ARRAY-BARS",
    contentType: "DRAGGABLE-ARRAY-BARS",
    answerType: "CHECK-ANSWER",
    hasAnswerOptions: false,
  },
  {
    qTimer: 10,
    qTopic: "MERGE",
    qType: "STATE-AFTER-SWAPS",
    contentType: "ARRAY-BARS",
    answerType: "ARRAY-BARS",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "MERGE",
    qType: "TIME-COMPLEXITY-DIRECT",
    contentType: "TEXT",
    answerType: "TEXT",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "MERGE",
    qType: "SPACE-COMPLEXITY",
    contentType: "TEXT",
    answerType: "TEXT",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "MERGE",
    qType: "CHOOSE-PSEUDOCODE",
    contentType: "CODE",
    answerType: "TEXT",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "MERGE",
    qType: "TIME-COMPLEXITY-FROM-ARRAY",
    contentType: "ARRAY-BARS",
    answerType: "TEXT",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "MERGE",
    qType: "DRAG-CODE",
    contentType: "DRAGGABLE-CODE",
    answerType: "CHECK-ANSWER",
    hasAnswerOptions: false,
  },
  {
    qTimer: 10,
    qTopic: "MERGE",
    qType: "DRAG-ARRAY-BARS",
    contentType: "DRAGGABLE-ARRAY-BARS",
    answerType: "CHECK-ANSWER",
    hasAnswerOptions: false,
  },
  {
    qTimer: 10,
    qTopic: "QUICK",
    qType: "STATE-AFTER-SWAPS",
    contentType: "ARRAY-BARS",
    answerType: "ARRAY-BARS",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "QUICK",
    qType: "TIME-COMPLEXITY-DIRECT",
    contentType: "TEXT",
    answerType: "TEXT",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "QUICK",
    qType: "SPACE-COMPLEXITY",
    contentType: "TEXT",
    answerType: "TEXT",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "QUICK",
    qType: "CHOOSE-PSEUDOCODE",
    contentType: "CODE",
    answerType: "TEXT",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "QUICK",
    qType: "TIME-COMPLEXITY-FROM-ARRAY",
    contentType: "ARRAY-BARS",
    answerType: "TEXT",
    hasAnswerOptions: true,
  },
  {
    qTimer: 10,
    qTopic: "QUICK",
    qType: "DRAG-CODE",
    contentType: "DRAGGABLE-CODE",
    answerType: "CHECK-ANSWER",
    hasAnswerOptions: false,
  },
  {
    qTimer: 10,
    qTopic: "QUICK",
    qType: "DRAG-ARRAY-BARS",
    contentType: "DRAGGABLE-ARRAY-BARS",
    answerType: "CHECK-ANSWER",
    hasAnswerOptions: false,
  },
];

export default gameQuestionList;
